### ISSUE TITLE
keybind

### ISSUE THREAD

**Issue by mihalyvig0202** [Puntzi/pnt_cruiseControl#4]
I can't change the original 'CAPITAL' keybind. Whatever I type, it will always work with 'CAPITAL'.

**Comment by Puntzi** [comment]
Ye because that will change for new players, but u need to change it from fivem configuration keys

**Comment by mihalyvig0202** [comment]
Thanks for the answer, I'm looking for it... :D (Unfortunately, I don't understand it, I can't find the solution. My fault.) It's perfect anyway, that's exactly what I've been looking for for a long time. I need it for driving school because of the speed.
