### ISSUE TITLE
Unwanted Chat spam

### ISSUE THREAD

**Issue by WhosHaci** [Puntzi/pnt_cruiseControl#6]
![image_2024-03-28_141608815](https://github.com/Puntzi/pnt_cruiseControl/assets/40610550/cab53803-2d01-4e2c-85f6-1be93d704ff5)
The text at the top right keeps appearing while I enable and disable the cruise control is there anyway to remove the top right text?

Edit update: Even if I'm not in a vehicle and I push the keybind for Cruise control it still shows the text in the top right.

**Comment by Puntzi** [comment]
Go to client.lua line 56 and 85 and delete the - sign. If that doesnt work then maybe its your chat script problem.

**Comment by WhosHaci** [comment]
It was a + sign but either way removing it from both lines as fixed the issue thanks for the quick reply and help!
